apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <html>
      <body>
        <h1>Ini tampilan dari NGINX dan nama saya Juanda Patra</h1>
      </body>
    </html>
