apiVersion: v1
kind: Service
metadata:
  name: simple-nginx-service
  namespace: nginx
spec:
  type: NodePort
  selector:
    app: simple-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082
