apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-index
data:
  index.html: |
    <html>
      <body>
        <h1>Ini tampilan dari HTTPD dan nama saya Juanda Patra 1</h1>
      </body>
    </html>
