apiVersion: v1
kind: Service
metadata:
  name: simple-httpd-service
  namespace: httpd
spec:
  type: NodePort
  selector:
    app: simple-httpd
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
